/*******************************************************************************
*
* Copyright 2017 SAP SE
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You should have received a copy of the License along with this
* program. If not, you may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
*******************************************************************************/

package collector

import (
	"errors"
	"sort"
	"testing"

	"github.com/gophercloud/gophercloud"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/sapcc/limes/pkg/db"
	"github.com/sapcc/limes/pkg/limes"
	"github.com/sapcc/limes/pkg/test"
)

func prepareScrapeTest(t *testing.T, quotaPlugins ...limes.QuotaPlugin) *test.Driver {
	test.ResetTime()
	test.InitDatabase(t, "../test/migrations")

	cluster := &limes.Cluster{
		ID:              "west",
		IsServiceShared: map[string]bool{},
		QuotaPlugins:    map[string]limes.QuotaPlugin{},
		CapacityPlugins: map[string]limes.CapacityPlugin{},
	}
	for _, plugin := range quotaPlugins {
		info := plugin.ServiceInfo()
		cluster.ServiceTypes = append(cluster.ServiceTypes, info.Type)
		cluster.QuotaPlugins[info.Type] = plugin
	}
	sort.Strings(cluster.ServiceTypes)

	driver := test.NewDriver(cluster)

	//one domain and one project is enough
	domainUUID1 := driver.StaticDomains[0].UUID
	driver.StaticDomains = driver.StaticDomains[0:1]
	driver.StaticProjects = map[string][]limes.KeystoneProject{
		domainUUID1: driver.StaticProjects[domainUUID1][0:1],
	}

	//ScanDomains is required to create the entries in `domains`, `domain_services`
	_, err := ScanDomains(driver, ScanDomainsOpts{})
	if err != nil {
		t.Fatal(err)
	}

	return driver
}

func Test_Scrape(t *testing.T) {
	plugin := test.NewPlugin("unittest")
	driver := prepareScrapeTest(t, plugin)
	c := Collector{
		Driver:          driver,
		Plugin:          plugin,
		LogError:        t.Errorf,
		TimeNow:         test.TimeNow,
		Once:            true,
		AutoAlignQuotas: true,
	}

	//check that ScanDomains created the domain, project and their services
	test.AssertDBContent(t, "fixtures/scrape0.sql")

	//first Scrape should create the entries in `project_resources` with the
	//correct usage and backend quota values (and quota = 0 because nothing was approved yet)
	//and set `project_services.scraped_at` to the current time
	plugin.SetQuotaFails = true
	c.Scrape()
	test.AssertDBContent(t, "fixtures/scrape1.sql")

	//second Scrape should not change anything (not even the timestamps) since
	//less than 30 minutes have passed since the last Scrape()
	c.Scrape()
	test.AssertDBContent(t, "fixtures/scrape1.sql")

	//change the data that is reported by the plugin
	plugin.StaticResourceData["capacity"].Quota = 110
	plugin.StaticResourceData["things"].Usage = 5
	setProjectServicesStale(t)
	//Scrape should pick up the changed resource data
	c.Scrape()
	test.AssertDBContent(t, "fixtures/scrape2.sql")

	//set some non-zero quota values so that we can discriminate them from zero
	_, err := db.DB.Exec(`UPDATE project_resources SET quota = ? WHERE name = ?`, 20, "capacity")
	if err != nil {
		t.Fatal(err)
	}
	_, err = db.DB.Exec(`UPDATE project_resources SET quota = ? WHERE name = ?`, 13, "things")
	if err != nil {
		t.Fatal(err)
	}

	//Scrape should try to enforce quota values in the backend (this did not work
	//until now because the test.Plugin was instructed to have SetQuota fail)
	plugin.SetQuotaFails = false
	setProjectServicesStale(t)
	c.Scrape()
	test.AssertDBContent(t, "fixtures/scrape3.sql")

	//another Scrape (with SetQuota disabled again) should show that the quota
	//update was durable
	plugin.SetQuotaFails = true
	setProjectServicesStale(t)
	c.Scrape()
	test.AssertDBContent(t, "fixtures/scrape4.sql") //same as scrape3.sql except for scraped_at timestamp

	//check data metrics generated by this scraping pass
	registry := prometheus.NewPedanticRegistry()
	dmc := &DataMetricsCollector{ClusterID: driver.Cluster().ID}
	registry.MustRegister(dmc)
	test.APIRequest{
		Method:           "GET",
		Path:             "/metrics",
		ExpectStatusCode: 200,
		ExpectFile:       "fixtures/scrape_metrics.json",
	}.Check(t, promhttp.HandlerFor(registry, promhttp.HandlerOpts{}))
}

func setProjectServicesStale(t *testing.T) {
	//make sure that the project is scraped again
	_, err := db.DB.Exec(`UPDATE project_services SET stale = ?`, true)
	if err != nil {
		t.Fatal(err)
	}
}

////////////////////////////////////////////////////////////////////////////////
// test for auto-approval

type autoApprovalTestPlugin struct {
	StaticBackendQuota uint64
}

func (p *autoApprovalTestPlugin) ServiceInfo() limes.ServiceInfo {
	return limes.ServiceInfo{
		Type: "autoapprovaltest",
	}
}

func (p *autoApprovalTestPlugin) Resources() []limes.ResourceInfo {
	//one resource can auto-approve, one cannot because BackendQuota != AutoApproveInitialQuota
	return []limes.ResourceInfo{
		{
			Name: "approve",
			AutoApproveInitialQuota: p.StaticBackendQuota,
		},
		{
			Name: "noapprove",
			AutoApproveInitialQuota: p.StaticBackendQuota,
		},
	}
}

func (p *autoApprovalTestPlugin) Scrape(provider *gophercloud.ProviderClient, domainUUID, projectUUID string) (map[string]limes.ResourceData, error) {
	return map[string]limes.ResourceData{
		"approve":   {Usage: 0, Quota: int64(p.StaticBackendQuota)},
		"noapprove": {Usage: 0, Quota: int64(p.StaticBackendQuota) + 10},
	}, nil
}

func (p *autoApprovalTestPlugin) SetQuota(provider *gophercloud.ProviderClient, domainUUID, projectUUID string, quotas map[string]uint64) error {
	return errors.New("unimplemented")
}

func Test_AutoApproveInitialQuota(t *testing.T) {
	plugin := &autoApprovalTestPlugin{StaticBackendQuota: 10}
	driver := prepareScrapeTest(t, plugin)
	c := Collector{
		Driver:   driver,
		Plugin:   plugin,
		LogError: t.Errorf,
		TimeNow:  test.TimeNow,
		Once:     true,
	}

	//when first scraping, the initial backend quota of the "approve" resource
	//shall be approved automatically
	c.Scrape()
	test.AssertDBContent(t, "fixtures/scrape-autoapprove1.sql")

	//modify the backend quota; verify that the second scrape does not
	//auto-approve the changed value again (auto-approval is limited to the
	//initial scrape)
	plugin.StaticBackendQuota += 10
	setProjectServicesStale(t)
	c.Scrape()
	test.AssertDBContent(t, "fixtures/scrape-autoapprove2.sql")
}
