// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company
// SPDX-License-Identifier: Apache-2.0

package core

import (
	"bytes"
	"errors"
	"fmt"
	"html/template"
	"time"

	"github.com/sapcc/go-api-declarations/limes"
	"github.com/sapcc/go-api-declarations/liquid"

	"github.com/sapcc/limes/internal/db"
)

// CommitmentGroupNotification contains data for rendering mails notifying about commitment workflows (confirmation or expiration).
type CommitmentGroupNotification struct {
	DomainName  string
	ProjectName string
	Commitments []CommitmentNotification
}

// AZResourceLocation is a tuple identifying an AZ resource within a project.
type AZResourceLocation struct {
	ServiceType      db.ServiceType
	ResourceName     liquid.ResourceName
	AvailabilityZone limes.AvailabilityZone
}

// ScopeString returns a human-readable string representation of this AZ resource location.
// Format: "<service_type>/<resource_name> in <availability_zone>"
func (a AZResourceLocation) ScopeString() string {
	return fmt.Sprintf("%s/%s in %s", a.ServiceType, a.ResourceName, a.AvailabilityZone)
}

// ShortScopeString returns a compact string representation of this AZ resource location.
// Format: "<service_type>/<resource_name>/<availability_zone>"
func (a AZResourceLocation) ShortScopeString() string {
	return fmt.Sprintf("%s/%s/%s", a.ServiceType, a.ResourceName, a.AvailabilityZone)
}

// CommitmentNotification appears in type CommitmentGroupNotification.
type CommitmentNotification struct {
	Commitment     db.ProjectCommitment
	DateString     string
	Resource       AZResourceLocation
	LeftoverAmount uint64
}

// MailTemplate is a template for notification mails generated by Limes.
// It appears in type MailTemplateConfiguration.
type MailTemplate struct {
	Subject  string             `json:"subject"`
	Body     string             `json:"body"`
	Compiled *template.Template `json:"-"` // filled during Config.Validate()
}

// Compile compiles the provided mail body template.
// This needs to be run once before any call to Render().
func (t *MailTemplate) Compile() (err error) {
	t.Compiled, err = template.New("mail-body").Parse(t.Body)
	return err
}

// Render generates a mail notification for a completed commitment workflow.
func (t MailTemplate) Render(m CommitmentGroupNotification, projectID db.ProjectID, now time.Time) (db.MailNotification, error) {
	if len(m.Commitments) == 0 {
		return db.MailNotification{}, fmt.Errorf("mail: no commitments provided for projectID: %v", projectID)
	}

	if t.Subject == "" {
		return db.MailNotification{}, fmt.Errorf("mail: subject is empty for projectID: %v", projectID)
	}
	body, err := t.getMailContent(m)
	if err != nil {
		return db.MailNotification{}, err
	}
	if body == "" {
		return db.MailNotification{}, fmt.Errorf("mail: body has no content. Check the mail template. Halted at projectID: %v", projectID)
	}

	notification := db.MailNotification{
		ProjectID:        projectID,
		Subject:          t.Subject,
		Body:             body,
		NextSubmissionAt: now,
	}

	return notification, nil
}

func (t MailTemplate) getMailContent(m CommitmentGroupNotification) (string, error) {
	var ioBuffer bytes.Buffer
	tpl := t.Compiled
	if tpl == nil {
		return "", errors.New("mail: body is empty. Check the accessibility of the mail template")
	}

	err := tpl.Execute(&ioBuffer, m)
	if err != nil {
		return "", err
	}

	return ioBuffer.String(), nil
}
