DROP TABLE cluster_services;
DROP TABLE cluster_resources;
DROP TABLE domains;
DROP TABLE domain_services;
DROP TABLE domain_resources;
DROP TABLE projects;
DROP INDEX project_services_stale_idx;
DROP TABLE project_services;
DROP TABLE project_resources;
